imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    templating:
        engines: ['twig']
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Doctrine Configuration
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options:
              username: "%mongodb_username%"
              password: "%mongodb_password%"
    default_database: "%mongodb_database%"
    document_managers:
        default:
            auto_mapping: true

jms_serializer:
    handlers:
        datetime:
            default_format: "U"
            default_timezone: "UTC"
    property_naming:
        separator: _
        lower_case: true
    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true

fos_rest:
    versioning: true
    body_listener: true
    exception:
        enabled: true
        messages:
            Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
    view:
        view_response_listener: true
        failed_validation: HTTP_BAD_REQUEST
    serializer:
        serialize_null: true
    body_converter:
        enabled: true
    format_listener:
        rules:
            - { path: "^/api",  priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }

# RabbitMQ configuration
enqueue:
    transport:
        default: 'rabbitmq_amqp'
        rabbitmq_amqp:
          dsn: 'amqp://rabbitmq:rabbitmq@localhost:5672/'
          delay_strategy: delayed_message_plugin
    client:
        traceable_producer:   true
        prefix:               cardrop
        app_name:             cardrop
        router_topic:         default
        router_queue:         default
        router_processor:     enqueue.client.router_processor
        default_processor_queue: default
        redelivered_delay_time: 0

thormeier_breadcrumb:
    template: '@Admin/Blocks/breadcrumbs.html.twig'

gos_web_socket:
    server:
        port: 8080
        host: 0.0.0.0
        router:
            resources:
                - "@WebSocketBundle/Resources/config/routing.yml"