root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/dashboard
        permanent: true
client:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

